services:
  redis:
    image: 'redis:latest'
    ports:
      - '63793:6379'

  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=sample'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=sample'
    ports:
      - '33063:3306'
